apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-devops-pvc
  namespace: demo-devops
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
