apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-devops-autoscaler
  namespace: demo-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-devops-dp
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 210Mi
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
